const images = {

   BEHAVIORAL_ECOLOGY: {
      ECOSYSTEM_ENERGY_FLOW: require('./BEHAVIORAL_ECOLOGY/ECOSYSTEM_ENERGY_FLOW.jpg')
   },
   BASIC: {
      EXPERIMENT_MEASURE_RATE_P_S: require('./BASIC/EXPERIMENT_MEASURE_RATE_P-S.gif'),
      CELL_ANATOMY: require('./BASIC/CELL_ANATOMY.png'),
      CELL_DIVISION: require('./BASIC/CELL_DIVISION.png'),
      GOLGI_APPARATUS: require('./BASIC/GOLGI_APPARATUS.gif'),
      LEAF_STRUCTURE: require('./BASIC/LEAF_STRUCTURE.gif'),
      MOTOR_NEURONE: require('./BASIC/MOTOR_NEURONE.gif'),
      PROTEIN_SYNTHESIS: require('./BASIC/PROTEIN_SYNTHESIS.png')
   },
   CANCER_BIOLOGY: {
      ANTIBACTERIAL_DRUG_CLASSES: require('./CANCER_BIOLOGY/ANTIBACTERIAL_DRUG_CLASSES.png'),
      BACTERIAL_INFECTIONS: require('./CANCER_BIOLOGY/BACTERIAL_INFECTIONS.png') 
   },
   CELL_BIOLOGY: {
      ASP_AND_GLU: require('./CELL_BIOLOGY/ASP_and_GLU.jpg'),
      CELL_CYCLE: require('./CELL_BIOLOGY/CELL_CYCLE.png'),
      DEHYDRATION_SYNTHESIS_CARBOHYDRATES: require('./CELL_BIOLOGY/DEHYDRATION_SYNTHESIS_CARBOHYDRATES.jpg'),
      DEHYDRATION_SYNTHESIS_LIPIDS: require('./CELL_BIOLOGY/DEHYDRATION_SYNTHESIS_LIPIDS.jpg'),
      ENDOCYTOSIS: require('./CELL_BIOLOGY/ENDOCYTOSIS.png'),
      HYDROLYSIS_CARBOHYDRATES: require('./CELL_BIOLOGY/HYDROLYSIS_CARBOHYDRATES.jpg'),
      HYDROLYSIS_IN_PROTEINS: require('./CELL_BIOLOGY/hydrolysis_in_proteins.jpg'),
      HYDROLYSIS_LIPIDS: require('./CELL_BIOLOGY/HYDROLYSIS_LIPIDS.jpg'),
      AMINO_ACIDS: require('./CELL_BIOLOGY/AMINO_ACIDS.jpg'),
      AMINO_ACIDS_DEHYDRATION: require('./CELL_BIOLOGY/AMINO_ACIDS_DEHYDRATION.jpg'),
      ENDOCYTOSIS_AND_EXOCYTOSIS: require('./CELL_BIOLOGY/ENDOCYTOSIS_AND_EXOCYTOSIS.jpeg'),
      MONOSACCHARIDE: require('./CELL_BIOLOGY/MONOSACCHARIDE.jpeg'),
      OSMOREGULATION: require('./CELL_BIOLOGY/OSMOREGULATION.gif'),
      PASSIVE_ACTIVE_TRANSPORT: require('./CELL_BIOLOGY/PASSIVE_ACTIVE_TRANSPORT.png'),
      PASSIVE_VS_ACTIVE_TRANSPORT: require('./CELL_BIOLOGY/PASSIVE_VS_ACTIVE_TRANSPORT.jpeg'),
      POLYSACCHARIDES: require('./CELL_BIOLOGY/POLYSACCHARIDES.jpeg'),
      POLYSATURATED_FATS: require('./CELL_BIOLOGY/POLYSATURATED_FATS.jpg'),
      PLASMA_MEMBRANE_SUPPORT: require('./CELL_BIOLOGY/PLASMA_MEMBRANE_SUPPORT.jpeg'),
      SATURATED_FATS: require('./CELL_BIOLOGY/SATURATED_FATS.jpeg')
   },   
   DEVELOPMENT:{
      PROTEIN_STRUCTURE: require('./DEVELOPMENT/PROTEIN_STRUCTURE.png')
   },
   ECOLOGY: {       
       CARBON_CYCLE: require('./ECOLOGY/Carbon_Cycle.jpg'),
       FOOD_CHAIN: require('./ECOLOGY/Food_Chain.jpg'),
       FOOD_WEBS: require('./ECOLOGY/Food_Webs.jpg'),
       NITROGEN_CYCLE: require('./ECOLOGY/Nitrogen_Cycle.jpg'),
       PYRAMID_BIOMASS: require('./ECOLOGY/Pyramid_Biomass.jpeg'),
       PYRAMID_ENERGY: require('./ECOLOGY/Pyramid_Energy.gif'),
       PYRAMID_NUMBERS: require('./ECOLOGY/Pyramid_Numbers.png'),
       SOIL_PROFILE: require('./ECOLOGY/Soil_Profile.jpg'),
       WATER_CYCLE: require('./ECOLOGY/Water_Cycle.jpg'),
       LOGISTIC_GROWTH: require('./ECOLOGY/LOGISTIC_GROWTH.gif')
   },
   GENE_REGULATION: {
      DNA_REPLICATION: require('./GENE_REGULATION/DNA_REPLICATION.png'),
      DNA_REPLICATION_IMAGE: require('./GENE_REGULATION/DNA_REPLICATION_IMAGE.png'),
      MUTATIONS: require('./GENE_REGULATION/MUTATIONS.gif'),
      TRANSCRIPTION_TRANSLATION: require('./GENE_REGULATION/TRANSCRIPTION_TRANSLATION.png'),
      TRANSCRIPTION: require('./GENE_REGULATION/TRANSCRIPTION.jpg'),
      TRANSLATION: require('./GENE_REGULATION/TRANSLATION.png')
   },
   GENETICS: {      
      BARR_BODIES: require('./GENETICS/BARR_BODIES.jpg'),
      CROSSING_OVER: require('./GENETICS/CROSSING_OVER.jpg'),
      GENOTYPE: require('./GENETICS/GENOTYPE.png'),      
      MEOSIS: require('./GENETICS/MEOSIS.png'),
      MITOSIS: require('./GENETICS/MITOSIS.png'),
      MEIOSIS: require('./GENETICS/MEIOSIS.jpg'),
      MEIOSIS_2: require('./GENETICS/MEIOSIS_2.png'),
      NONDISJUNCTION_MEIOSIS: require('./GENETICS/NONDISJUNCTION_MEIOSIS.jpg'),
      PHENOTYPE: require('./GENETICS/PHENOTYPE.jpg'),
      PUNNET_SQUARES_CODOMINANCE: require('./GENETICS/PUNNET_SQUARES_CODOMINANCE.jpg'),
      PUNNET_SQUARES_DIHYBRID: require('./GENETICS/PUNNET_SQUARES_DIHYBRID.jpg'),
      PUNNET_SQUARES_INCOMPLETE_DOMINANCE: require('./GENETICS/PUNNET_SQUARES_INCOMPLETE_DOMINANCE.jpg'),
      PUNNET_SQUARES_MONOHYBRID: require('./GENETICS/PUNNET_SQUARES_MONOHYBRID.png'),
      TEST_CROSS_IMAGE: require('./GENETICS/TEST_CROSS_IMAGE.jpg'),
      ZYGOTE: require('./GENETICS/ZYGOTE.png')
   },   
   HOST_PATHOGEN_INTERACTIONS: {
      ANGULAR_CHEILLITIS: require('./HOST_PATHOGEN_INTERACTIONS/ANGULAR_CHEILLITIS.png'),
      CANDIDA: require('./HOST_PATHOGEN_INTERACTIONS/CANDIDA.png'),
      CARIES_ETIOLOGY_CONCEPTS:require('./HOST_PATHOGEN_INTERACTIONS/CARIES_ETIOLOGY_CONCEPTS.png'),
      DIPHTHERIA:require('./HOST_PATHOGEN_INTERACTIONS/DIPHTHERIA.png'),
      DIPHTHERIA_PSEUDOMEMBRANOUS_LESION:require('./HOST_PATHOGEN_INTERACTIONS/DIPHTHERIA_PSEUDOMEMBRANOUS_LESION.png'),
      ERYSIPELA: require('./HOST_PATHOGEN_INTERACTIONS/ERYSIPELA.png'),
      GRAM_POSITIVE_BACTERIA_LAB_ALGORITHM: require('./HOST_PATHOGEN_INTERACTIONS/GRAM_POSITIVE_BACTERIA_LAB_ALGORITHM.png'),
      PHARYNGOTONSILITIS: require('./HOST_PATHOGEN_INTERACTIONS/PHARYNGOTONSILITIS.png'),
      POST_STREPTOCOCCAL_GLOMERULO_NEPHRITIS: require('./HOST_PATHOGEN_INTERACTIONS/PHARYNGOTONSILITIS.jpg'),
      PAROVIRUS_B19: require('./HOST_PATHOGEN_INTERACTIONS/PAROVIRUS_B19.jpg'),
      KEYES_NEWBRUN_TRIADS:require('./HOST_PATHOGEN_INTERACTIONS/KEYES_NEWBRUN_TRIADS.png'),
      RHEUMATIC_FEVER:require('./HOST_PATHOGEN_INTERACTIONS/RHEUMATIC_FEVER.png'),
      SCARLET_FEVER:require('./HOST_PATHOGEN_INTERACTIONS/SCARLET_FEVER.png'),
      STREPTOCOCCI:require('./HOST_PATHOGEN_INTERACTIONS/STREPTOCOCCI.png'),
      VINCENTS_ANGINA:require('./HOST_PATHOGEN_INTERACTIONS/VINCENTS_ANGINA.png')
   },
   MICROBIOLOGY: {
      ISOMERS: require('./MICROBIOLOGY/ISOMERS.png'),
      MITOCHONDRIA: require('./MICROBIOLOGY/MITOCHONDRIA.png'),
      NONCYCLIC_PHOTOPHOSPHORYLATION: require('./MICROBIOLOGY/NONCYCLIC_PHOTOPHOSPHORYLATION.png'),
      CITRIC_ACID_KREBS_CYCLE: require('./MICROBIOLOGY/CITRIC_ACID_KREBS_CYCLE.png'),
      CYCLIC_PHOTOPHOSPHORYLATION: require('./MICROBIOLOGY/CYCLIC_PHOTOPHOSPHORYLATION.png'),
      ETC_OXIDATAIVE_PHOTOPHORYLATION_CHEMIOSMOSIS: require('./MICROBIOLOGY/ETC_OXIDATAIVE_PHOTOPHORYLATION_CHEMIOSMOSIS.jpg'),
      CALVIN_CYCLE: require('./MICROBIOLOGY/CALVIN_CYCLE.png')
   },
   PLANT_BIOLOGY:{
      ANGIOSPERM_REPRODUCTION: require('./PLANT_BIOLOGY/ANGIOSPERM_REPRODUCTION.gif'),
      GAMETOPHYTE_SPRORPHYTE_CYCLE: require('./PLANT_BIOLOGY/GAMETOPHYTE_SPRORPHYTE_CYCLE.jpg'),
      GYMNOSPERMS_VS_ANGIOSPERMS: require('./PLANT_BIOLOGY/GYMNOSPERMS_VS_ANGIOSPERMS.png'),
      SEED_DEVELOPEMENT: require('./PLANT_BIOLOGY/SEED_DEVELOPEMENT.jpg')
   },
   SYSTEMS_BIOLOGY: {
      EYE_STRUCTURE: require('./SYSTEMS_BIOLOGY/EYE_STRUCTURE.jpg'),
      LOOK_UP_AND_FAR: require('./SYSTEMS_BIOLOGY/LOOK_UP_AND_FAR.jpg'),
      OPTIC_NERVES: require('./SYSTEMS_BIOLOGY/OPTIC_NERVES.jpg'),
      POSITIONING: require('./SYSTEMS_BIOLOGY/POSITIONING.png'),      
      SMALL_INTESTINE_ADAPTATIONS: require('./SYSTEMS_BIOLOGY/SMALL_INTESTINE_ADAPTATIONS.gif'),
      TAB_STRUCTURE: require('./SYSTEMS_BIOLOGY/TAB_STRUCTURE.jpg')
   },
   beaker: require('./beaker.jpg'),
}

export default images;